### ISSUE TITLE
ISAAC params

### ISSUE THREAD

**Issue by Arash1381-y** [Accelergy-Project/accelergy-library-plug-in#2]
I was checking the ISAAC primitive components and I missed some of the equations so I wanted to ask you about them.

1) DAC Area comment include extra 128 division(the area in table is correct although): 

$` \text{DAC AREA} = (170 mm^2)/(8 \times 128 \times128) `$

2) Energy of ADC

why power is divided by $`1.2 \times 10^7`$. Does this number come from the 1.2 GHz frequency? Why is it divided by 100? I also do not understand the underutilization coefficient.  i am not sure about this number based on the fact that the energy consumption off 8 ADCs become smaller than 128 DACs in a pipeline cycle.

3) Energy of eDRAM BUS

Based on the paper, the slowest stage is the crossbar latency(100 ns). I am not sure why ADC/DAC consumption time is used for it. Can you explain it to me?

**Comment by tanner-andrulis** [comment]
1. Fixed
2. Are you talking about library/isaac/isaac_adc.csv ? It is divided by 1.2E9 (The ADC frequency)
3. The ADCs run at 1.2GHz and require 107ns to process all 128 columns. We calculated using this number.
